{% set name = "yaozarrs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b8554a52475ba9d2680ef65482fc00c494d3b783b20d4d4ae512e03d1281e42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - yaozarrs = yaozarrs._cli:main

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pydantic >=2.5.0
    - typing-extensions >=4.6.0

test:
  imports:
    - yaozarrs.v04
    - yaozarrs.v05
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/yaozarrs
  summary: 'Yet Another OME-Zarr Schema & Utils'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://tlambert03.github.io/yaozarrs/
  dev_url: https://github.com/tlambert03/yaozarrs

extra:
  recipe-maintainers:
    - tlambert03
